import { TailwindIndicator, ThemeProvider } from "@planet-matrix/components"

import type { Metadata } from "next"

import "@planet-matrix/tailwind-preset/index.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
        <TailwindIndicator />
      </body>
    </html>
  )
}
